import path from 'node:path'
import { HOME } from './safety.js'

export type Group = 'dev' | 'xcode' | 'system' | 'bulk' | 'advisory'

/** How a target is emptied: wipe the directory itself, or only its children. */
export type Mode = 'self' | 'contents'

export interface Target {
  id: string
  group: Group
  label: string
  /** What is lost, and how it comes back. Shown before anything is deleted. */
  recovery: string
  mode: Mode
  paths: string[]
}

const home = (...segments: string[]) => path.join(HOME, ...segments)

export const GROUP_LABELS: Record<Group, string> = {
  dev: 'Dev caches',
  xcode: 'Xcode junk',
  system: 'Trash, logs & .DS_Store',
  bulk: 'Duplicate installs',
  advisory: 'Big, but your call',
}

export const TARGETS: Target[] = [
  {
    id: 'npm',
    group: 'dev',
    label: 'npm cache',
    recovery: 'refetched on next install',
    mode: 'contents',
    paths: [home('.npm', '_cacache')],
  },
  {
    id: 'pnpm',
    group: 'dev',
    label: 'pnpm store',
    recovery: 'refetched on next install',
    mode: 'contents',
    paths: [home('Library', 'pnpm', 'store'), home('.pnpm-store')],
  },
  {
    id: 'yarn',
    group: 'dev',
    label: 'yarn cache',
    recovery: 'refetched on next install',
    mode: 'contents',
    paths: [home('Library', 'Caches', 'Yarn')],
  },
  {
    id: 'bun',
    group: 'dev',
    label: 'bun cache',
    recovery: 'refetched on next install',
    mode: 'contents',
    paths: [home('.bun', 'install', 'cache')],
  },
  {
    id: 'homebrew',
    group: 'dev',
    label: 'Homebrew downloads',
    recovery: 're-downloaded on next brew install',
    mode: 'contents',
    paths: [home('Library', 'Caches', 'Homebrew')],
  },
  {
    id: 'pip',
    group: 'dev',
    label: 'pip cache',
    recovery: 'refetched on next pip install',
    mode: 'contents',
    paths: [home('Library', 'Caches', 'pip')],
  },
  {
    id: 'cargo',
    group: 'dev',
    label: 'cargo registry cache',
    recovery: 'refetched on next cargo build',
    mode: 'contents',
    paths: [home('.cargo', 'registry', 'cache'), home('.cargo', 'registry', 'src')],
  },
  {
    id: 'gradle',
    group: 'dev',
    label: 'Gradle caches',
    recovery: 'rebuilt on next Gradle run (slow first build)',
    mode: 'contents',
    paths: [home('.gradle', 'caches')],
  },
  {
    id: 'derived-data',
    group: 'xcode',
    label: 'Xcode DerivedData',
    recovery: 'rebuilt on next Xcode build',
    mode: 'contents',
    paths: [home('Library', 'Developer', 'Xcode', 'DerivedData')],
  },
  {
    id: 'archives',
    group: 'xcode',
    label: 'Xcode archives',
    recovery: 'GONE — re-archive needed to resymbolicate old crash logs',
    mode: 'contents',
    paths: [home('Library', 'Developer', 'Xcode', 'Archives')],
  },
  {
    id: 'device-support',
    group: 'xcode',
    label: 'iOS DeviceSupport',
    recovery: 're-extracted when that iOS device is reconnected',
    mode: 'contents',
    paths: [
      home('Library', 'Developer', 'Xcode', 'iOS DeviceSupport'),
      home('Library', 'Developer', 'Xcode', 'watchOS DeviceSupport'),
    ],
  },
  {
    id: 'simulator-caches',
    group: 'xcode',
    label: 'Simulator caches',
    recovery: 'regenerated by the simulator',
    mode: 'contents',
    paths: [
      home('Library', 'Developer', 'CoreSimulator', 'Caches'),
      home('Library', 'Developer', 'CoreSimulator', 'Devices', 'Restore'),
    ],
  },
  {
    id: 'trash',
    group: 'system',
    label: 'Trash',
    recovery: 'GONE — this is the point of the Trash',
    mode: 'contents',
    paths: [home('.Trash')],
  },
  {
    id: 'logs',
    group: 'system',
    label: 'User logs',
    recovery: 'regenerated by apps as they run',
    mode: 'contents',
    paths: [home('Library', 'Logs')],
  },
]

export function targetsForGroups(groups: Group[]): Target[] {
  return TARGETS.filter((target) => groups.includes(target.group))
}
